In [1]:
import numpy as np

In [2]:
x=[1,2,3,4,5]

In [3]:
type(x)

list

In [4]:
# We use the np.array function to convert this list into array

In [8]:
arr=np.array(x)

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [ ]:
# We we want range of values in the array we use 'arange' function/operation

In [11]:
np.arange(1,15) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(1,11,2) # There will be difference of 2 in the elements fro 1 to 10 i.e 3-1=2 and so

array([1, 3, 5, 7, 9])

In [14]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [15]:
np.zeros((2,4))  # two dimensonal array with two rows and four columns , we use zeros function so it will give this.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# when we want to generate some random numbers in the array so we use random.randint function where we specify the range and 
# how many random no. we want to gerenate.

In [24]:
arr1= np.random.randint(1,1000,50)

In [25]:
arr1

array([553, 303, 548, 457, 916, 525, 439, 935, 356, 347, 259, 526, 646,
       312, 162, 273, 156, 504, 872, 521, 530,  26, 592,   2, 842, 561,
       190, 929, 585, 724, 965, 225, 912, 645, 921, 182, 647,   3, 293,
       652, 314,  67, 527, 373, 667, 716, 122, 828, 576, 312])

In [ ]:
# when we execute this so everytime it will give us different random numbers 

In [32]:
arr1= np.random.randint(1,1000,50)

In [33]:
arr1

array([964, 220, 702, 761, 291, 438, 159,  56, 530, 708, 118, 622, 649,
       442, 807, 142, 838,  88,  70, 242,  53, 642,  50,   4, 279, 668,
       344, 867, 452, 510, 618, 642, 505, 319, 420, 920, 436,  96, 756,
       478, 341, 789, 510, 795, 309, 638, 913, 175, 753, 996])

In [ ]:
# So as we perform different operations and functions on this it will be problamatic so we use 'random.seed function' and 
# pass some arbitary value so it will not gonna change the value on execution and random no.s will remain constant

In [30]:
np.random.seed(51)
arr1= np.random.randint(1,1000,50)

In [31]:
arr1

array([ 58, 486, 737, 970, 710, 529, 918, 735, 437, 362, 934, 635, 879,
       550, 573, 863,  29, 853, 677, 164, 924, 999,  29, 427, 885, 907,
         7, 794, 418, 462, 501, 936, 305,  25, 681,  55, 718, 885,  29,
       838, 570, 787, 192,  76, 708, 253, 351, 472, 904, 766])

In [34]:
np.random.seed(51)
arr1= np.random.randint(1,1000,50)

In [35]:
arr1

array([ 58, 486, 737, 970, 710, 529, 918, 735, 437, 362, 934, 635, 879,
       550, 573, 863,  29, 853, 677, 164, 924, 999,  29, 427, 885, 907,
         7, 794, 418, 462, 501, 936, 305,  25, 681,  55, 718, 885,  29,
       838, 570, 787, 192,  76, 708, 253, 351, 472, 904, 766])

In [ ]:
# until now arr1 is of one dim array so if we want to convert it into 2d array we use 'reshape' function 

In [36]:
arr1.reshape(5,10)

array([[ 58, 486, 737, 970, 710, 529, 918, 735, 437, 362],
       [934, 635, 879, 550, 573, 863,  29, 853, 677, 164],
       [924, 999,  29, 427, 885, 907,   7, 794, 418, 462],
       [501, 936, 305,  25, 681,  55, 718, 885,  29, 838],
       [570, 787, 192,  76, 708, 253, 351, 472, 904, 766]])

In [37]:
arr1.reshape(10,5)

array([[ 58, 486, 737, 970, 710],
       [529, 918, 735, 437, 362],
       [934, 635, 879, 550, 573],
       [863,  29, 853, 677, 164],
       [924, 999,  29, 427, 885],
       [907,   7, 794, 418, 462],
       [501, 936, 305,  25, 681],
       [ 55, 718, 885,  29, 838],
       [570, 787, 192,  76, 708],
       [253, 351, 472, 904, 766]])

In [38]:
arr1.reshape(10,10)

ValueError: cannot reshape array of size 50 into shape (10,10)

In [39]:
arr1.reshape(5,5)

ValueError: cannot reshape array of size 50 into shape (5,5)